# Generated by Django 3.1.5 on 2021-03-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.BooleanField(choices=[(True, 'Activé'), (False, 'Désactivé')], default=True),
        ),
    ]
