# Generated by Django 3.1.5 on 2021-03-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210312_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slogan',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
