# Generated by Django 3.1.5 on 2021-03-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210317_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthyear',
            field=models.IntegerField(null=True),
        ),
    ]
