# Generated by Django 3.1.5 on 2021-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210318_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='facebook_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='instagram_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='twitter_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gig',
            name='website_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
