# Generated by Django 3.1.5 on 2021-03-25 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20210318_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='price',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
