# Generated by Django 3.1.5 on 2021-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210325_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rate',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
