# Generated by Django 3.1.5 on 2021-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210325_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_nb_bad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
