# Generated by Django 3.1.5 on 2021-04-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_review_rating_nb_bad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='photo',
            field=models.FileField(default='gigs/baramogo-default-gig-1.jpeg', upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatars/avatar-default-1.jpeg', upload_to='avatars'),
        ),
    ]
