# Generated by Django 3.1.5 on 2021-04-09 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210402_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='ggeoloc_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='ggeoloc_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='ggeoloc_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('ggeoloc_url', models.CharField(max_length=1000, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ggeoloc_url', models.CharField(max_length=1000, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
    ]
