# Generated by Django 3.1.5 on 2021-04-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210413_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.locality'),
        ),
        migrations.AddField(
            model_name='gig',
            name='subarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subarea'),
        ),
    ]
