# Generated by Django 3.1.5 on 2021-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210413_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='photo',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='gig',
            name='images',
            field=models.FileField(default='gigs/baramogo-default-gig-1.jpeg', upload_to='gigs'),
            preserve_default=False,
        ),
    ]
