# Generated by Django 3.1.5 on 2021-05-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210529_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GigImage',
        ),
    ]
