# Generated by Django 3.1.5 on 2021-05-29 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_gigimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='gigs')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gig')),
            ],
        ),
    ]
