# Generated by Django 3.1.5 on 2021-06-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_gigimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatars/avatar-default-1.png', upload_to='avatars'),
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.TimeField(null=True)),
                ('time_close', models.TimeField(null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.day')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gig')),
            ],
        ),
    ]
