# Generated by Django 3.1.5 on 2021-06-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210626_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessHours',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
