# Generated by Django 3.1.5 on 2023-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210627_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthyear',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
