# Generated by Django 3.1.5 on 2023-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20230717_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='avatars/user.png', upload_to='avatars'),
        ),
    ]
