# Generated by Django 3.1.5 on 2023-08-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20230726_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='city',
        ),
        migrations.RemoveField(
            model_name='subarea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='area',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='country',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='subarea',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
        migrations.DeleteModel(
            name='SubArea',
        ),
        migrations.AddField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
