# Generated by Django 3.1.5 on 2023-08-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20230803_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='address',
        ),
    ]
