# Generated by Django 3.1.5 on 2023-08-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_gig_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='location',
            new_name='address',
        ),
    ]
