# Generated by Django 3.1.5 on 2023-08-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20230803_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='cover_image',
            field=models.FileField(upload_to='gigs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to='avatars'),
        ),
    ]
